name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            name: mac
          - os: windows-latest
            name: win
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Compile
        run: deno task compile
      - name: Pack
        shell: bash
        run: |
          cp coeiroink-v2-bridge.exe ./build_resources/ || true
          cp coeiroink-v2-bridge ./build_resources/ || true
          cp providers/icon.png ./build_resources/
          cd build_resources
          7z a -tzip coeiroink-bridge-${{ github.ref_name }}-${{ matrix.name }}.zip *
          mv coeiroink-bridge-${{ github.ref_name }}-${{ matrix.name }}.zip coeiroink-bridge-${{ github.ref_name }}-${{ matrix.name }}.vvpp

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            coeiroink-bridge-${{ github.ref_name }}-${{ matrix.name }}.vvpp
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
