name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Compile
        run: deno task compile
      - name: Pack
        run: |
          cp coeiroink-v2-bridge.exe ./build_resources/
          cd build_resources
          compress-archive . ../coeiroink-bridge-${{ github.ref_name }}.vvpp

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            coeiroink-bridge-${{ github.ref_name }}.vvpp
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
